version: '3.8'
services:
    main:
        build:
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=127.0.0.1'
        volumes:
            - .:/app
        ports:
            - 8000:80
